services:
  QM1:
    container_name: QM1
    image: icr.io/ibm-messaging/mq:latest
    ports:
      - '1414:1414'
      - '9443:9443'
    environment:
      - MQ_QMGR_NAME=QM1
      - MQ_APP_USER=app
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_USER=admin
      - MQ_ADMIN_PASSWORD=passw0rd
      - LICENSE=accept
    volumes:
      - qm1data:/mnt/mqm
volumes:
  qm1data:
